parameters:
#    diet_user.example.class: Diet\UserBundle\Example

services:
#    diet_user.example:
#        class: %diet_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
