parameters:
#    diet_core.example.class: Diet\CoreBundle\Example

services:
#    diet_core.example:
#        class: %diet_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
