Diet\CoreBundle\Entity\Target:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        month_target:
            type: integer
        week_target:
            type: integer
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]
    manyToOne:
        user:
            targetEntity: User
            inversedBy: targets