parameters:
#    diet_admin.example.class: Diet\AdminBundle\Example

services:
#    diet_admin.example:
#        class: %diet_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
